### ISSUE TITLE
Chrome extension "not logged in"

### ISSUE THREAD

**Issue by SkouRene** [TimeLog/TimeLogApiSdk#1]
After I added the TimeLog chrome extension, when i go to a new tab it still says that I have to login, even when I'am logged in on another tab.

Chrome Version 44.0.2403.125 (64-bit)
OS: linux mint 17

**Comment by madslundholmdk** [comment]
I have made a PR that should fix this issue #2

**Comment by oexenhave** [comment]
Hi Rene. I have just pushed the changes from @MadsLundholmDk to the Chrome store. I'm not familiar with the release schedules in Chrome, but it should at least be available for download/update within an hour. Thanks @MadsLundholmDk
