### ISSUE TITLE
Reporting API / ServiceSoapClient / GetWorkingHoursRaw no data before 27-06-2018

### ISSUE THREAD

**Issue by DBFBlackbull** [TimeLog/TimeLogApiSdk#11]
If I use the GetWorkingHoursRaw betweeb 01-05-2018 to 30-04-2019, then the earliest I get data for is 27-06-2018.

The documentation does not state that there is any cut off date, where no date before this point is returned.

Please return the data or update the documentation to specify what the limits of the API are.

**Comment by oexenhave** [comment]
Hi @DBFBlackbull 

We don't have a cut off date on that specific call, so you should receive all data from the system. I'll have to know more details about which site in order to investigate further. Please email the details to support@timelog.com so we can have a developer look into it.

**Comment by DBFBlackbull** [comment]
Hey. I had a chat with your support that informed me that the data was missing due to our company upgrading from an older version to a new version of timelog on that date.

I have written code to handle this in my send. Cheers for the help
