### ISSUE TITLE
API for closing weekly hoursheet?

### ISSUE THREAD

**Issue by johanot** [TimeLog/TimeLogApiSdk#13]
Hey Timelog,

We use your SOAP API's for certain timelogging operations.

I was wondering whether the operation of submitting a weekly hoursheet ("indsend til godkendelse") can be made available through the API? Or is it already - have I missed it?

![image](https://user-images.githubusercontent.com/998763/78229207-f672ea80-74cf-11ea-955d-0a675d93cb43.png)

Thanks in advance.

**Comment by oexenhave** [comment]
@lewisgauss I believe this is exactly what we are working on for a coming release in the REST API? Please elaborate here, thanks.

**Comment by lwschan** [comment]
Hello @johanot, @oexenhave is right. We will be working on new timesheet related REST APIs. However, I am unable to give a timeline for the release now.
