### ISSUE TITLE
Tag-Name typo mistake in GetProjectsRaw?

### ISSUE THREAD

**Issue by mvh-bskies** [TimeLog/TimeLogApiSdk#18]
I stumbled upon the following:

`CustomerID` != `CustomerId`

## The steps to reproduce

Getting a Project with `GetProjectsRaw`.

Returns a Project with Xml Element of Customer like so:
https://github.com/TimeLog/TimeLogApiSdk/blob/28111c9f8b11a8ac93e8a1e3b62f4976df25ae13/TimeLog.Api.Documentation/Source/Reporting/GetProjectsRaw.xml#L16

Deserializing Xml to Project with providing a Project XmlNode to ctor.
From the ctor
https://github.com/TimeLog/TimeLogApiSdk/blob/28111c9f8b11a8ac93e8a1e3b62f4976df25ae13/TimeLog.ReportingApi.SDK/Project.cs#L69

Results in a Customer value of 0 because of initial value from here:
https://github.com/TimeLog/TimeLogApiSdk/blob/28111c9f8b11a8ac93e8a1e3b62f4976df25ae13/TimeLog.ReportingApi.SDK/Project.cs#L27

Probably Proof of my consumption:
Inheriting from Project with member like this gets the information
```csharp
    class MyProject : Project
    {
        int CustomerID
        {
            get { return base.CustomerId; }
            set { base.CustomerId = value; }
        }
        MyProject(XmlNode node, XmlNamespaceManager manager) : base(node, manager)
        {
            CustomerID = node.GetIntSafe("tlp:CustomerID", manager);
        }
    }
```

I'm not pretty sure if I misunderstood something. If this Issue is some kind of nonsense, please ignore.
Otherwise I hope this is some kind of helpfull.

**Comment by oexenhave** [comment]
Hi @mvh-bskies. You are correct. We have inconsistent use of Id vs. ID. I have pushed a correction. Thanks for reporting!
