### ISSUE TITLE
Where is the javascript sample?

### ISSUE THREAD

**Issue by Ruffio** [TimeLog/TimeLogApiSdk#21]
According to the website (https://api.timelog.com/) there should be a javascript sample, but where is it?
![image](https://user-images.githubusercontent.com/1877612/97167299-dd40cc80-1786-11eb-95a0-e00687a31f21.png)

**Comment by oexenhave** [comment]
Hi @Ruffio. I'm sorry we haven't replied to your request earlier. We realized that our sample got out of date and wasn't representable as a good sample - so we decided to delete it. You will be able to find it going back in the repo history though...

I know long time has passed, did you manage to find another way around this?

**Comment by Ruffio** [comment]
Sorry, I ended up ditching the project as there were no support for it.
