### ISSUE TITLE
GetContractCustomersRaw.xsd is missing from documentation

### ISSUE THREAD

**Issue by Nisden** [TimeLog/TimeLogApiSdk#33]
https://api.timelog.com/Reporting/Method/TimeLogTLPWebAppCodeServiceGetContractCustomersRaw does not have a link to its .xsd file, and the .xsd file is not found at https://api.timelog.com/Source/Reporting/GetContractCustomersRaw.xsd either (like the others)

**Comment by lwschan** [comment]
I have looked into this. The documentation exists in the Source folder, but the documentation website is not updated. 
This will be fixed with an update to the website.

**Comment by lwschan** [comment]
The .xsd file is available from https://github.com/TimeLog/TimeLogApiSdk/blob/master/TimeLog.Api.Documentation/Source/Reporting/GetContractCustomersRaw.xsd

![image](https://user-images.githubusercontent.com/8966669/110885981-cb6d5980-8322-11eb-8dff-767dc7b9d8a2.png)

**Comment by lwschan** [comment]
Website was updated. https://api.timelog.com/Reporting/Method/TimeLogTLPWebAppCodeServiceGetContractCustomersRaw #40
