### ISSUE TITLE
ProjectManagementService - Missing operation GetProjectByID 

### ISSUE THREAD

**Issue by Alpalhao** [TimeLog/TimeLogApiSdk#4]
Hi TimeLog Team,
On the documentation of "Project Management Service" there is a reference to the operation "Get Project ID", but on the SDK and WSDL this operation does not exist.

If was removed, how i can get all the details of a Project? 
Like: Project Currency, Department, Ordered by Department.. basically all the information i see on the screen  of a a Project

Thank you in advance.

**Comment by oexenhave** [comment]
I'm sorry, we didn't manage to follow up on your issue in due time. I hope you managed to find a workaround or filed a support ticket at support@timelog.com. Even though it is way overdue at this point, I suggest you update the associated SDK DLLs as it should have been added at this point at least.

And again. Sorry, we will be better.
