### ISSUE TITLE
Please update the TimeLog.ApiConsoleApp to .net5

### ISSUE THREAD

**Issue by DBFBlackbull** [TimeLog/TimeLogApiSdk#43]
Currently the TimeLog.ApiConsoleApp is .NETFramework 4.8 which makes it impossible to reference the SDK libraries, as the SDK libraries are in .NET5.

Please update so it once again becomes possible to access this information

**Comment by lwschan** [comment]
Hi @DBFBlackbull 

Apologies for the slow action from our end. We have just updated our solution and the projects to .NET 6 - which means it's gonna be a breaking change. You may pull again to get the update. 

Thanks for your patience and letting us know about this.
