### ISSUE TITLE
Error on ProjectManagementService / GetProjectByExternalKey

### ISSUE THREAD

**Issue by Alpalhao** [TimeLog/TimeLogApiSdk#5]
Hi TimeLog Team,

When i call the service ProjectManagementService / GetProjectByExternalKey, i getting the follow error: 

**Error during call on TimeLog.API, Message 'Specified cast is not valid.'**

Sound like an error on de service itself, because if i try with a invalid systemName i get a different error: 

**Error during call on TimeLog.API, Message 'Unable to retrieve result from SP: TSP_Project_Select_By_Id with ID 00000000-0000-0000-0000-000000000000**

Can you check what's wrong on the API

Thanks

**Comment by oexenhave** [comment]
I'm sorry, we didn't manage to follow up on your issue in due time. I hope you managed to find a workaround or filed a support ticket at support@timelog.com. Even though it is way overdue at this point, I suggest you double check if the external system actually exists, from the error I believe it doesn't.

And again. Sorry, we will be better.
