### ISSUE TITLE
CreateSubTaskAsync always returns an error

### ISSUE THREAD

**Issue by MMThornberg** [TimeLog/TimeLogApiSdk#7]
I have tried sending a Task object for the following scenarios:
- ProjectSubContractID = 0
- ProjectSubContractID = <int value greater then 0>
- ProjectSubContractID not present

For all of the scenarios listed above I get this error:
"Error during call on TimeLog.API, Message 'ProjectSubContractID has to be > 0 on Task. Current value: 0'"

Meanwhile "CreateTaskAsync" works fine.

"Fun" fact:
API doc at https://api.timelog.com/Transactional/Method/TimeLogTLPAPIProjectManagementV1_7ProjectManagementServiceCreateSubTask states: "Put Task.ProjectSubContractID to 0 to inherit from the contract of the parent task". Clearly this in incorrect.

/Michael

**Comment by MMThornberg** [comment]
It might be relevant that the property ProjectSubContractID is not available in the ProjectTaskFlat object type.

**Comment by oexenhave** [comment]
The documentation refers to the latest version of TimeLog. However, by the looks of it your site is not actually on that version. That doesn't explain why it failed, so I'll make sure someone follow on this and get back to you. I see you have created a support case already through support@timelog.com, so I'll close this Github issue.
